_BASE_: ../maskformer_R50_bs32_60k.yaml
MODEL:
  BACKBONE:
    NAME: "D2ShuntedTransformer" 
  WEIGHTS: "ShuntedTransformer_B.pth"  
  PIXEL_MEAN: [71.947, 131.126, 75.773]
  PIXEL_STD: [38.609, 34.434, 43.401]
  SEM_SEG_HEAD:
    PIXEL_DECODER_NAME: "DUpsamplepixelDecoder"
  MASK_FORMER:
    TRANSFORMER_IN_FEATURE: "res5"
    ENFORCE_INPUT_PROJ: True
    TEST:
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
SOLVER:
  BASE_LR: 0.00006
  WARMUP_FACTOR: 1e-6
  WARMUP_ITERS: 1500
  WEIGHT_DECAY: 0.01
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_EMBED: 0.0
  BACKBONE_MULTIPLIER: 1.0